name: tests

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: make
      run: make

    - name: run unit tests
      run: make run-unit-tests

    - name: run lint tests
      run: make test
