name: tests

on:
  push:
    branches: [ "main" ]

jobs:
  gdblint:
    name: build and test gdblint
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./gdblint

    steps:
    - uses: actions/checkout@v4

    - name: make
      run: make

    - name: run unit tests
      run: make run-unit-tests

    - name: test stdout
      run: ./bin/gdblint ./tests/testscript_01_undefined_var.gdb

    - name: test stdout 2
      run: ./bin/gdblint -l

    - name: run lint tests
      run: ./tests/testrunner ./tests
