name: tests

on:
  push:
    branches: [ "main" ]

jobs:
  gdblint:
    name: build and test gdblint
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./gdblint

    steps:
    - uses: actions/checkout@v4

    - name: make
      run: make

    - name: run unit tests
      run: make run-unit-tests

    - name: install strace
      run: sudo apt install -y strace

    - name: strace print help
      run: |
        strace ./bin/gdblint -h;
        exit 0

    - name: strace print arch
      run: strace ./bin/gdblint -l

    - name: test stdout print help
      run: ./bin/gdblint -h

    - name: test stdout print arch
      run: ./bin/gdblint -l

    - name: test stdout
      run: ./bin/gdblint ./tests/testscript_01_undefined_var.gdb

    - name: run lint tests
      run: ./tests/testrunner ./tests
