name: tests

on:
  push:
    branches: [ "main" ]

jobs:
  gdblint:
    name: build and test gdblint
    runs-on: ubuntu-latest

    defaults:
      working-directory: ./gdblint

    steps:
    - uses: actions/checkout@v4

    - name: make
      run: make

    - name: run unit tests
      run: make run-unit-tests

    - name: run lint tests
      run: make test
