name: tests

on:
  push:
    branches: [ "main" ]

jobs:
  gdblint:
    name: build and test gdblint
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./gdblint

    steps:
    - uses: actions/checkout@v4

    - name: install gdb
      run: sudo apt install -y gdb

    - name: make
      run: make

    - name: run unit tests
      run: make run-unit-tests

    - name: install strace
      run: sudo apt install -y strace

    - name: objdump gdblint print_arch
      run: objdump -d ./bin/gdblint | grep -A 40 "<print_arch>:";

    - name: objdump gdblint print_help
      run: objdump -d ./bin/gdblint | grep -A 40 "<print_help>:";

    - name: strace hashmap test
      run: |
        set +e
        strace ./tests/unit/bin/hashmap
        exit 0

    - name: strace print arch
      run: |
        set +e
        strace ./bin/gdblint -l
        exit 0

    - name: strace print help
      run: |
        set +e
        strace ./bin/gdblint -h
        exit 0

    - name: test stdout print help
      run: |
        set +e
        ./bin/gdblint -h
        exit 0

    - name: test stdout print arch
      run: ./bin/gdblint -l

    - name: test stdout
      run: |
        set +e
        ./bin/gdblint ./tests/testscript_01_undefined_var.gdb
        exit 0

    - name: run lint tests
      run: ./tests/testrunner ./tests
